language: csharp
solution: src/Optivem.Commons.Persistence.EntityFramework.sln

dotnet: 2.2
mono: none
sudo: required
dist: xenial

script:
    - cd src
    - dotnet restore
    - dotnet build -c Release