title: Optivem .NET Commons Persistence EntityFramework
description: Implementation of generic repository and generic unit of work using EntityFramework
google_analytics: UA-63306472-4
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions